# Generated by Django 5.2.7 on 2026-02-13 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Сумма бюджета (общая)')),
            ],
            options={
                'verbose_name': 'Бюджет',
                'verbose_name_plural': 'Бюджет',
            },
        ),
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование продукции')),
                ('quantity', models.FloatField(default=0.0, verbose_name='Остаток')),
                ('amount', models.FloatField(default=0.0, verbose_name='Общая стоимость остатка')),
            ],
            options={
                'verbose_name': 'Готовая продукция',
                'verbose_name_plural': 'Готовая продукция',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование сырья')),
                ('quantity', models.FloatField(default=0.0, verbose_name='Остаток')),
                ('amount', models.FloatField(default=0.0, verbose_name='Общая стоимость остатка')),
            ],
            options={
                'verbose_name': 'Сырьё',
                'verbose_name_plural': 'Сырьё',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оклад')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Количество произведенного')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.employee', verbose_name='Сотрудник')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.finishedproduct', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Производство',
                'verbose_name_plural': 'Производство',
            },
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('amount', models.FloatField(verbose_name='Сумма продажи')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.employee', verbose_name='Сотрудник')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.finishedproduct', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Продажа продукции',
                'verbose_name_plural': 'Продажи продукции',
            },
        ),
        migrations.CreateModel(
            name='RawPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Количестсво')),
                ('amount', models.FloatField(verbose_name='Сумма закупки')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.employee', verbose_name='Сотрудник')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.rawmaterial', verbose_name='Сырьё')),
            ],
            options={
                'verbose_name': 'Закупка сырья',
                'verbose_name_plural': 'Закупки сырья',
            },
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.unit', verbose_name='Ед. изм.'),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.unit', verbose_name='Ед. изм.'),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Количество на 1 ед. продукции')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.finishedproduct', verbose_name='Продукция')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.rawmaterial', verbose_name='Сырьё')),
            ],
            options={
                'verbose_name': 'Ингредиент (Состав)',
                'verbose_name_plural': 'Ингредиенты (Состав)',
                'unique_together': {('product', 'raw_material')},
            },
        ),
    ]
