# Generated by Django 5.2.12 on 2026-03-06 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_seed_workwear_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Сумма кредита')),
                ('date_taken', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
            ],
            options={
                'verbose_name': 'Бизнес-кредит',
                'verbose_name_plural': 'Бизнес-кредиты',
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Сумма выплаты')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выплаты')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Выплата зарплаты',
                'verbose_name_plural': 'Выплаты зарплаты',
            },
        ),
    ]
