# Generated by Django 5.2.7 on 2026-04-17 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_businessloan_salarypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('status', models.CharField(choices=[('Создана', 'Создана'), ('На проверке наличия сырья', 'На проверке наличия сырья'), ('На процессе закупки сырья', 'На процессе закупки сырья'), ('На процессе производства', 'На процессе производства'), ('На процессе продажи', 'На процессе продажи'), ('Выполнена', 'Выполнена'), ('Ошибка', 'Ошибка')], default='Создана', max_length=50, verbose_name='Статус')),
                ('applicant_name', models.CharField(max_length=200, verbose_name='ФИО заявителя')),
                ('quantity', models.FloatField(verbose_name='Количество продукции')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Причина отказа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.finishedproduct', verbose_name='Готовая продукция')),
            ],
            options={
                'verbose_name': 'Заявка на производство',
                'verbose_name_plural': 'Заявки на производство',
            },
        ),
    ]
