# Generated by Django 5.2.12 on 2026-04-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_productionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='min_price',
            field=models.FloatField(default=0.0, help_text='Минимальная / базовая цена закупки за 1 единицу', verbose_name='Мин. цена за единицу'),
        ),
    ]
